name: untitled
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  english_words: ^4.0.0
  hexcolor: ^2.0.7
  location: ^4.2.0
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  get: ^4.6.5


flutter:

  uses-material-design: true

  assets:
    - assets/drawable/ic_scan_qr.png
    - assets/drawable/ic_information.png
    - assets/drawable/ic_profile.png
    - assets/drawable/ic_dvr.png
    - assets/drawable/ic_qvin.png
  #   - drawable/a_dot_burr.jpeg
  #   - drawable/a_dot_ham.jpeg
