name: untitled
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  english_words: ^4.0.0
  hexcolor: ^2.0.7
  location: ^4.2.0
  provider: ^5.0.0
  dio: ^4.0.6
  http: ^0.13.5
  shared_preferences: ^2.0.6
  qr_code_scanner: ^1.0.1
  flutter_spinkit: ^5.1.0
  carousel_slider: ^4.1.1
  sqflite: ^2.0.0+3
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  get: ^4.6.5


flutter:

  uses-material-design: true

  assets:
    - assets/drawable/ic_scan_qr.png
    - assets/drawable/ic_information.png
    - assets/drawable/ic_profile.png
    - assets/drawable/ic_dvr.png
    - assets/drawable/ic_qvin.png
    - assets/drawable/rectangle.png
    - assets/drawable/truck1.png
    - assets/drawable/truck2.png
    - assets/drawable/truck3.png
    - assets/drawable/truck4.png
  #   - drawable/a_dot_burr.jpeg
  #   - drawable/a_dot_ham.jpeg
